branch-defaults:
  develop2:
    environment: product-dbapp-stg1
  master:
    environment: product-dbapp
environment-defaults:
  product-dbapp-stg1:
    branch: null
    repository: null
  product-dbapp-stg3:
    branch: develop2
    repository: product-db
global:
  application_name: product-dbapp
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-1::platform/Puma with Ruby
    2.5 running on 64bit Amazon Linux/2.8.5
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
